package world

import (
	"errors"
	"fmt"
	"reflect"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"
)

const (
	// RoomPostOfficeFlag is RPOSTO from src/mtype.h. The legacy room flag
	// values are zero based even though docs/rom_flag prints their one-based
	// display number.
	RoomPostOfficeFlag = 10
	RoomPostOffice     = RoomPostOfficeFlag

	// Mail IDs are generated by the persistence boundary. The limit keeps a
	// corrupt snapshot from turning validation or receipt rendering into an
	// unbounded allocation.
	MaxMailMessageIDBytes = 128
	// The legacy editor bounds each input line to 79 bytes but has no aggregate
	// file limit. The canonical slice keeps the source line-oriented behavior
	// representable while imposing a finite durable body limit.
	MaxMailBodyBytes = 64 * 1024
	MaxMailboxes     = 100000
	MaxMailboxSize   = 10000

	MailReadResponseEmpty = "받은 편지가 없습니다.\n"
	MailDeleteResponse    = "편지가 삭제되었습니다.\n"
	MailRoomResponse      = "이곳은 우체국이 아닙니다.\n"
	MailTimestampFormat   = "Mon Jan _2 15:04:05 2006"
)

var (
	ErrMailActorAbsent   = errors.New("online canonical mail actor absent")
	ErrMailNotPostOffice = errors.New("mail command requires a post office room")
	ErrMailMessage       = errors.New("invalid canonical mail message")
)

// MailMessage is one durable letter in a recipient's ordered mailbox.
//
// SenderID is the canonical character identity. Sender is retained as a
// source/display compatibility field for imported snapshots: when it is an
// identity it must equal SenderID; when it is a display name it must exactly
// match the canonical sender name and the name must resolve unambiguously.
// New writers should set SenderID and leave Sender empty. Keeping both fields
// lets old normalized fixtures be admitted without ever trusting a client
// supplied sender during a command.
type MailMessage struct {
	ID        string    `json:"id"`
	SenderID  string    `json:"sender_id,omitempty"`
	Sender    string    `json:"sender,omitempty"`
	Body      string    `json:"body"`
	Timestamp time.Time `json:"timestamp"`
}

// MailAction is deliberately closed. MailSend is the canonical one-message
// append used by the world domain; collecting the legacy interactive editor's
// lines remains an adapter/session concern.
type MailAction string

const (
	MailRead   MailAction = "read"
	MailDelete MailAction = "delete"
	MailSend   MailAction = "send"
)

// MailResult is the deterministic actor response persisted by the session
// receipt. Read includes a copy of the ordered messages; delete includes the
// IDs removed and whether the candidate changed canonical state. Eventful
// transport output is intentionally absent: post.c only addressed the actor.
type MailResult struct {
	Action     MailAction    `json:"action"`
	ActorID    string        `json:"actor_id"`
	Response   string        `json:"response"`
	Messages   []MailMessage `json:"messages,omitempty"`
	MessageIDs []string      `json:"message_ids,omitempty"`
	Deleted    int           `json:"deleted,omitempty"`
	Changed    bool          `json:"changed"`
}

// MailProposal captures the exact actor, room and mailbox preconditions used
// by ApplyMail. The fields are intentionally not client-facing; a proposal is
// only a candidate created from one State snapshot and must be revalidated
// before the state candidate is returned.
type MailProposal struct {
	Action             MailAction
	ActorID            string
	RoomID             int16
	ExpectedActor      PlayerState
	ExpectedRoomFlags  [8]byte
	ExpectedMailbox    []MailMessage
	ExpectedMailboxKey bool
	ExpectedMailboxes  bool
	ExpectedResponse   string
}

func validMailToken(value string, max int) bool {
	if value == "" || len(value) > max || !utf8.ValidString(value) || strings.TrimSpace(value) != value {
		return false
	}
	for _, r := range value {
		if unicode.IsSpace(r) || unicode.IsControl(r) || r == '\u2028' || r == '\u2029' {
			return false
		}
	}
	return true
}

func validMailDisplayName(value string) bool {
	if value == "" || !utf8.ValidString(value) || strings.TrimSpace(value) != value {
		return false
	}
	for _, r := range value {
		if unicode.IsControl(r) || unicode.IsSpace(r) || r == '\u2028' || r == '\u2029' {
			return false
		}
	}
	return true
}

// ValidateMailBody validates canonical body bytes without rejecting the LF
// separators that the legacy post editor writes after each line. Other
// controls, including CR and terminal escape sequences, are rejected so a
// migrated body cannot inject a prompt or protocol frame.
func ValidateMailBody(body string) error {
	if body == "" || !utf8.ValidString(body) || len(body) > MaxMailBodyBytes {
		return ErrMailMessage
	}
	for _, r := range body {
		if r == '\n' {
			continue
		}
		if unicode.IsControl(r) || r == '\u2028' || r == '\u2029' {
			return ErrMailMessage
		}
	}
	return nil
}

// resolveMailSender resolves a snapshot sender to a canonical player ID. A
// display-name-only imported record is admitted only when exactly one player
// has that name; ambiguous names fail closed rather than selecting by map
// iteration. Offline senders remain valid because mail outlives sessions.
func (s State) resolveMailSender(message MailMessage) (string, string, error) {
	if message.SenderID != "" {
		if !validMailToken(message.SenderID, MaxMailMessageIDBytes) {
			return "", "", ErrMailMessage
		}
		player, ok := s.Players[message.SenderID]
		if !ok || player.Body.Type != 0 || !validMailDisplayName(player.Body.Name) {
			return "", "", ErrMailMessage
		}
		if message.Sender != "" && message.Sender != message.SenderID && message.Sender != player.Body.Name {
			return "", "", ErrMailMessage
		}
		return message.SenderID, player.Body.Name, nil
	}
	if !validMailDisplayName(message.Sender) && !validMailToken(message.Sender, MaxMailMessageIDBytes) {
		return "", "", ErrMailMessage
	}
	if player, ok := s.Players[message.Sender]; ok {
		if player.Body.Type != 0 || !validMailDisplayName(player.Body.Name) {
			return "", "", ErrMailMessage
		}
		return message.Sender, player.Body.Name, nil
	}
	if message.Sender == "" {
		return "", "", ErrMailMessage
	}
	var resolvedID string
	for id, player := range s.Players {
		if player.Body.Type != 0 || player.Body.Name != message.Sender || !validMailDisplayName(player.Body.Name) {
			continue
		}
		if resolvedID != "" {
			return "", "", ErrMailMessage
		}
		resolvedID = id
	}
	if resolvedID == "" {
		return "", "", ErrMailMessage
	}
	return resolvedID, message.Sender, nil
}

func (s State) validateMailMessage(recipientID string, message MailMessage, seenIDs map[string]bool) error {
	if !validMailToken(message.ID, MaxMailMessageIDBytes) || seenIDs[message.ID] {
		return ErrMailMessage
	}
	if err := ValidateMailBody(message.Body); err != nil {
		return err
	}
	if message.Timestamp.IsZero() || message.Timestamp.Before(time.Unix(0, 0)) {
		return ErrMailMessage
	}
	if recipientID == "" {
		return ErrMailMessage
	}
	if _, _, err := s.resolveMailSender(message); err != nil {
		return err
	}
	seenIDs[message.ID] = true
	return nil
}

// validateMailboxes is called by State.Validate. It deliberately accepts nil
// as a pre-migration marker, while a nonnil map is checked completely and
// cannot contain a dangling recipient, duplicate message ID or unresolved
// sender.
func (s State) validateMailboxes() error {
	if s.Mailboxes == nil {
		return nil
	}
	if len(s.Mailboxes) > MaxMailboxes {
		return fmt.Errorf("mailbox count exceeds limit")
	}
	seenIDs := make(map[string]bool)
	for recipientID, messages := range s.Mailboxes {
		if !validMailToken(recipientID, MaxMailMessageIDBytes) {
			return fmt.Errorf("invalid mailbox recipient")
		}
		recipient, ok := s.Players[recipientID]
		if !ok || recipient.Body.Type != 0 {
			return fmt.Errorf("mailbox recipient absent")
		}
		if len(messages) > MaxMailboxSize {
			return fmt.Errorf("mailbox size exceeds limit")
		}
		for _, message := range messages {
			if err := s.validateMailMessage(recipientID, message, seenIDs); err != nil {
				return fmt.Errorf("invalid mail message %q: %w", message.ID, err)
			}
		}
	}
	return nil
}

// mailActor enforces the authoritative actor and RPOSTO room boundary. The
// room ID is always read from the canonical player body; no caller supplied
// room number participates in authorization.
func (s State) mailActor(actorID string) (PlayerState, RoomState, error) {
	if err := s.Validate(); err != nil {
		return PlayerState{}, RoomState{}, err
	}
	actor, ok := s.Players[actorID]
	if actorID == "" || !ok || !actor.Online || actor.Body.Type != 0 || !validMailDisplayName(actor.Body.Name) {
		return PlayerState{}, RoomState{}, ErrMailActorAbsent
	}
	room, ok := s.Rooms[actor.Body.RoomID]
	if !ok {
		return PlayerState{}, RoomState{}, ErrMailActorAbsent
	}
	if !flag(room.Resource.Flags[:], RoomPostOfficeFlag) {
		return PlayerState{}, RoomState{}, ErrMailNotPostOffice
	}
	return actor, room, nil
}

func copyMailMessages(messages []MailMessage) []MailMessage {
	if messages == nil {
		return nil
	}
	return append([]MailMessage{}, messages...)
}

func (s State) currentMailbox(actorID string) ([]MailMessage, bool) {
	if s.Mailboxes == nil {
		return nil, false
	}
	messages, ok := s.Mailboxes[actorID]
	return messages, ok
}

func sameMailMailbox(expected []MailMessage, expectedKey bool, current []MailMessage, currentKey bool) bool {
	return expectedKey == currentKey && reflect.DeepEqual(expected, current)
}

func (s State) mailProposal(actorID string, action MailAction) (MailProposal, error) {
	if action != MailRead && action != MailDelete {
		return MailProposal{}, fmt.Errorf("unsupported mail action")
	}
	actor, room, err := s.mailActor(actorID)
	if err != nil {
		return MailProposal{}, err
	}
	messages, present := s.currentMailbox(actorID)
	proposal := MailProposal{
		Action:             action,
		ActorID:            actorID,
		RoomID:             actor.Body.RoomID,
		ExpectedActor:      actor,
		ExpectedRoomFlags:  room.Resource.Flags,
		ExpectedMailbox:    copyMailMessages(messages),
		ExpectedMailboxKey: present,
		ExpectedMailboxes:  s.Mailboxes != nil,
	}
	if action == MailRead {
		response, err := s.formatMailbox(actorID, messages)
		if err != nil {
			return MailProposal{}, err
		}
		proposal.ExpectedResponse = response
	} else {
		proposal.ExpectedResponse = MailDeleteResponse
	}
	return proposal, nil
}

// PlanMailRead creates a no-state-change read candidate after checking the
// canonical actor and room. It intentionally snapshots the ordered mailbox so
// ApplyMail can reject a stale candidate instead of rendering mixed data.
func (s State) PlanMailRead(actorID string) (MailProposal, error) {
	return s.mailProposal(actorID, MailRead)
}

// PlanMailDelete creates the atomic whole-mailbox deletion candidate matching
// postdelete: the legacy command has no message selector and unlinks the
// recipient's complete mail file.
func (s State) PlanMailDelete(actorID string) (MailProposal, error) {
	return s.mailProposal(actorID, MailDelete)
}

func (s State) formatMailbox(actorID string, messages []MailMessage) (string, error) {
	if len(messages) == 0 {
		return MailReadResponseEmpty, nil
	}
	var out strings.Builder
	for _, message := range messages {
		_, senderName, err := s.resolveMailSender(message)
		if err != nil {
			return "", err
		}
		if err := ValidateMailBody(message.Body); err != nil {
			return "", err
		}
		fmt.Fprintf(&out, "\n---\n%s (%s)님에게서의 편지:\n\n%s", senderName, message.Timestamp.Format(MailTimestampFormat), message.Body)
		if !strings.HasSuffix(message.Body, "\n") {
			out.WriteByte('\n')
		}
	}
	return out.String(), nil
}

func (s State) staleMailProposal(proposal MailProposal) error {
	actor, room, err := s.mailActor(proposal.ActorID)
	if err != nil {
		return err
	}
	if proposal.ActorID == "" || proposal.RoomID != actor.Body.RoomID ||
		!reflect.DeepEqual(proposal.ExpectedActor, actor) || proposal.ExpectedRoomFlags != room.Resource.Flags ||
		proposal.ExpectedMailboxes != (s.Mailboxes != nil) {
		return fmt.Errorf("stale mail proposal")
	}
	messages, present := s.currentMailbox(proposal.ActorID)
	if !sameMailMailbox(proposal.ExpectedMailbox, proposal.ExpectedMailboxKey, messages, present) {
		return fmt.Errorf("stale mail proposal")
	}
	return nil
}

// ApplyMail rechecks the proposal and atomically returns the next State and
// typed actor result. Read returns the original state; delete clones and
// clears the recipient slice exactly once. Receipt/replay idempotency is owned
// by engine.Execute, so this pure reducer never performs a second deletion.
func (s State) ApplyMail(proposal MailProposal) (State, MailResult, error) {
	if proposal.Action != MailRead && proposal.Action != MailDelete {
		return State{}, MailResult{}, fmt.Errorf("unsupported mail action")
	}
	if err := s.staleMailProposal(proposal); err != nil {
		return State{}, MailResult{}, err
	}
	messages, _ := s.currentMailbox(proposal.ActorID)
	result := MailResult{Action: proposal.Action, ActorID: proposal.ActorID, Changed: false}
	switch proposal.Action {
	case MailRead:
		response, err := s.formatMailbox(proposal.ActorID, messages)
		if err != nil {
			return State{}, MailResult{}, err
		}
		if proposal.ExpectedResponse != "" && response != proposal.ExpectedResponse {
			return State{}, MailResult{}, fmt.Errorf("stale mail response")
		}
		result.Response = response
		result.Messages = copyMailMessages(messages)
		for _, message := range messages {
			result.MessageIDs = append(result.MessageIDs, message.ID)
		}
		return s, result, nil
	case MailDelete:
		result.Response = MailDeleteResponse
		result.Deleted = len(messages)
		if len(messages) == 0 {
			return s, result, nil
		}
		next := s.clone()
		if next.Mailboxes == nil {
			return State{}, MailResult{}, fmt.Errorf("mailbox migration marker disappeared")
		}
		next.Mailboxes[proposal.ActorID] = []MailMessage{}
		result.Changed = true
		for _, message := range messages {
			result.MessageIDs = append(result.MessageIDs, message.ID)
		}
		if err := next.Validate(); err != nil {
			return State{}, MailResult{}, err
		}
		return next, result, nil
	default:
		return State{}, MailResult{}, fmt.Errorf("unsupported mail action")
	}
}

// ApplyMailRead is the direct read convenience used by unit callers.
func (s State) ApplyMailRead(actorID string) (State, MailResult, error) {
	proposal, err := s.PlanMailRead(actorID)
	if err != nil {
		return State{}, MailResult{}, err
	}
	return s.ApplyMail(proposal)
}

// ApplyMailDelete is the direct whole-mailbox deletion convenience used by
// unit callers and session reducers.
func (s State) ApplyMailDelete(actorID string) (State, MailResult, error) {
	proposal, err := s.PlanMailDelete(actorID)
	if err != nil {
		return State{}, MailResult{}, err
	}
	return s.ApplyMail(proposal)
}

// Mailbox returns an independent copy of one canonical mailbox. It is a
// projection helper, not an authorization bypass: the actor must be online in
// an RPOSTO room just like the commands.
func (s State) Mailbox(actorID string) ([]MailMessage, error) {
	if _, _, err := s.mailActor(actorID); err != nil {
		return nil, err
	}
	messages, _ := s.currentMailbox(actorID)
	return copyMailMessages(messages), nil
}

// ReadMailbox returns the exact postread text for callers that do not need the
// typed reducer result. The session command persists MailResult instead.
func (s State) ReadMailbox(actorID string) (string, error) {
	_, result, err := s.ApplyMailRead(actorID)
	if err != nil {
		return "", err
	}
	return result.Response, nil
}

// ReadMail is the typed-result counterpart to ReadMailbox.
func (s State) ReadMail(actorID string) (MailResult, error) {
	_, result, err := s.ApplyMailRead(actorID)
	if err != nil {
		return MailResult{}, err
	}
	return result, nil
}

// DeleteMailbox applies postdelete and returns its typed outcome.
func (s State) DeleteMailbox(actorID string) (State, MailResult, error) {
	return s.ApplyMailDelete(actorID)
}

// DeleteMail is a concise typed alias for DeleteMailbox.
func (s State) DeleteMail(actorID string) (State, MailResult, error) {
	return s.ApplyMailDelete(actorID)
}
